const tasks = [
    {
        title: 'Complete Project Report',
        description: 'Prepare the final project report and send it to the stakeholders.',
        dueDate: '2024-09-30',
        status: 'In Progress',
        assignedUsers: ['Alice', 'Bob', 'Charlie'],
        priority: 'High',
    },
    {
        title: 'Complete Java Report',
        description: 'Prepare the final project report and send it to the stakeholders.',
        dueDate: '2024-09-30',
        status: 'In Progress',
        assignedUsers: ['Alice', 'Bob', 'Charlie'],
        priority: 'High',
    },
    {
        title: 'Complete Python Report',
        description: 'Prepare the final project report and send it to the stakeholders.',
        dueDate: '2024-09-30',
        status: 'In Progress',
        assignedUsers: ['Alice', 'Bob', 'Charlie'],
        priority: 'High',
    },
    {
        title: 'Complete C++ Report',
        description: 'Prepare the final project report and send it to the stakeholders.',
        dueDate: '2024-09-30',
        status: 'In Progress',
        assignedUsers: ['Alice', 'Bob', 'Charlie'],
        priority: 'High',
    },
    {
        title: 'Complete Microsoft Report',
        description: 'Prepare the final project report and send it to the stakeholders.',
        dueDate: '2024-09-30',
        status: 'In Progress',
        assignedUsers: ['Alice', 'Bob', 'Charlie'],
        priority: 'High',
    },
    {
        title: 'Complete CSS Report',
        description: 'Prepare the final project report and send it to the stakeholders.',
        dueDate: '2024-09-30',
        status: 'In Progress',
        assignedUsers: ['Alice', 'Bob', 'Charlie'],
        priority: 'High',
    },
    {
        title: 'Complete HTML Report',
        description: 'Prepare the final project report and send it to the stakeholders.',
        dueDate: '2024-09-30',
        status: 'In Progress',
        assignedUsers: ['Alice', 'Bob', 'Charlie'],
        priority: 'High',
    },
    {
        title: 'Complete C Report',
        description: 'Prepare the final project report and send it to the stakeholders.',
        dueDate: '2024-09-30',
        status: 'In Progress',
        assignedUsers: ['Alice', 'Bob', 'Charlie'],
        priority: 'High',
    },
    {
        title: 'Complete Java Report',
        description: 'Prepare the final project report and send it to the stakeholders.',
        dueDate: '2024-09-30',
        status: 'In Progress',
        assignedUsers: ['Alice', 'Bob', 'Charlie'],
        priority: 'High',
    },
    {
        title: 'Complete C# Report',
        description: 'Prepare the final project report and send it to the stakeholders.',
        dueDate: '2024-09-30',
        status: 'In Progress',
        assignedUsers: ['Alice', 'Bob', 'Charlie'],
        priority: 'High',
    },
    {
        title: 'Complete Golang Report',
        description: 'Prepare the final project report and send it to the stakeholders.',
        dueDate: '2024-09-30',
        status: 'In Progress',
        assignedUsers: ['Alice', 'Bob', 'Charlie'],
        priority: 'High',
    },
    {
        title: 'Complete Communication Report',
        description: 'Prepare the final project report and send it to the stakeholders.',
        dueDate: '2024-09-30',
        status: 'In Progress',
        assignedUsers: ['Alice', 'Bob', 'Charlie'],
        priority: 'High',
    },
]

export { tasks }